title: Portfolio Marlo Nickol
description: > # this means to ignore newlines until "baseurl:"
  Game Design Portfolio of Marlo Nickol. A Game Designer with some years of experience 
  and a background in computer science and QA. Creating games with people for people
  with the little extra that makes them more than just games.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https:marlonickol.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Marlo Nickol # add your name
author-img: marlo-nickol-portrait.png # add your photo
about-author: > 
  A Game Designer who is all about creating Games with people for people
  <br> - <br>
  with that little extra that makes them more than just games.
social-itch: marlogamedev
social-github: marlonickol # add your Github handle
social-linkedin: marlo-nickol # add your Linkedin handle
social-email: contact-marlo@mailbox.org # add your Email address

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
